services:
  ebank-discovery-service:
    build: ./discovery-service
    container_name: ebank-discovery-service
    ports:
      - '8761:8761'
    expose:
      - '8761'
    healthcheck:
      test: ["CMD","curl","-f","http://localhost:8761/actuator/health"]
      interval: 10s
  ebank-config-srevice:
    build: ./config-service
    container_name: ebank-config-srevice
    ports:
      - '9999:9999'
    expose:
      - '9999'
    depends_on:
      ebank-discovery-service:
        condition: service_healthy

